# Generated by Django 3.1.4 on 2020-12-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default=' test@test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
