# Generated by Django 3.1.4 on 2020-12-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
