# Generated by Django 3.1.4 on 2020-12-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201222_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='CATEGORY',
            field=models.CharField(choices=[('', ''), ('', '')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
