# Generated by Django 3.1.4 on 2020-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='CATEGORY',
            field=models.CharField(choices=[('DataBase deal', 'will view'), ('', '')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
